### ISSUE TITLE
com.sendbird.android.SendBirdException: WS connection closed.

### ISSUE THREAD

**Issue by pkb126** [smilefam/SendBird-Android#24]
I'm trying to send location as a user message using google place picker Intent.
On Button click call this

`PlacePicker.IntentBuilder builder = new PlacePicker.IntentBuilder();
           startActivityForResult(builder.build(activity), PLACE_PICKER_REQUEST);`

Now in onActivityResult()

`if (requestCode == PLACE_PICKER_REQUEST)`
`{`
       `  Place place = PlacePicker.getPlace(activity, data);`
        ` double latitude = place.getLatLng().latitude;`
       `  double longitude = place.getLatLng().longitude;`
`UserMessage tempUserMessage = mChannel.sendUserMessage(latitude+" "+longitude, new` `BaseChannel.SendUserMessageHandler() {`
            `@Override`
           ` public void onSent(final UserMessage userMessage, SendBirdException e) {`
                `if (e != null) {`
                    `// Error!`
                   ` Log.e(LOG_TAG, e.toString());`
                    `mChatAdapter.markMessageFailed(userMessage.getRequestId());`
                   ` return;`
            ` }`
                `// Update a sent message to RecyclerView`
              `  mChatAdapter.markMessageSent(userMessage);`
           ` }`
      `  });`
 `}`

I Don't know the connection is closing here, Please help me.

**Comment by sf-jay-yun** [comment]
Would you try with SendBird.setAutoBackgroundDetection(false) before you call PlacePicker? And please be sure to set it true again in onActivityResult().
You can refer to the sample where we implement sending images from gallery.

The reason is that SendBird SDK automatically detects whether the application is running foreground or in background and manages connection accordingly. When an external Activity like Gallery or PlacePicker pops up, the SDK regards the application's state as background and disconnects the socket connection. So if you disable auto background detection mode temporarily, the unwanted disconnection can be prevented.

**Comment by pkb126** [comment]
Hi sf-jay-yun

Thank for quick reply,

I tried with your solution but still, it's not working. my onActivityResult() look like this 
[https://codeshare.io/5NZpBm](url)

and I don't know why onResume() method called after onActivityResult()

Lot of people want to integrate location into there chatting app, 

Could you please make a demo using Google place picker in SDK example that will we be very helpful for all people.

Thanks again.

**Comment by sf-jay-yun** [comment]
Sorry for this belated reply.

Just found that you are calling SendBird.setAutoBackgroundDetection(true); at the end of onActivityResult(). Then even though you set SendBird.setAutoBackgroundDetection(false); before you start PlacePicker, the auto background detection mode will be set as true again.

You can refer GroupChatFragment.java for how the auto background detection is controlled especially in requestMedia() and onActivityResult().

We are also discussing internally to introduce location feature into the demo app.

**Comment by pkb126** [comment]
Thanks for your reply.

**Comment by sf-jay-yun** [comment]
Thanks. Will close the issue.
