### ISSUE TITLE
Push notifications as "data-messages"

### ISSUE THREAD

**Issue by marcosPerezRubio** [smilefam/SendBird-Android#9]
Hi again!

I'm developing my second app using SendBird, but this time using FCM.

I've a fully working chat but with the only that push notifications are not received if the app is killed since the notifications are lead to the system tray and the Firebase Services can not handle it.

After a little bit of research I found a possible solution that could do the trick. This solution is to send the messages as **data-messages** instead of **display-messages** only changing the structure of the JSON sent to FCM.

I don't know if it will be really hard (or impossible) to do, but I think that would be pretty awesome to have it! 

I really love your job guys! Congratulations and keep going with that :D

Some of the links that talk about it:

- http://stackoverflow.com/questions/37711082/how-to-handle-notification-when-app-in-background-in-firebase/37845174

- http://stackoverflow.com/a/37845174/4756582

**Comment by terrykwon** [comment]
@marcosPerezRubio I'm very sorry for the late reply - we were in the process of working on the problem you encountered, and are very glad to say that it should've been fixed in recent updates 😄 . 

Another solution that might be relevant to your case is to implement **Webhooks**, which you can use to monitor events that occur within channels and inflate custom notifications. Here's the link to our docs: https://docs.sendbird.com/platform#webhooks
